---
- name: FLATPAK | Enable Flathub repository
  become: yes
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak

- name:  FLATPAK | Install Spotify flatpak
  flatpak:
    name: com.spotify.Client
    method: system
  tags:
    - flatpak

- name: FLATPAK | Install Signal flatpak
  flatpak:
    name: org.signal.Signal
    method: system
  tags:
    - flatpak

- name: FLATPAK |  Install Skype flatpak
  flatpak:
    name: com.skype.Client
    method: system
  tags:
    - flatpak
    - flatpak-avoidable
    - skype

- name: FLATPAK |  Install Slack flatpak
  flatpak:
    name: com.slack.Slack
    method: system
  tags:
    - flatpak
    - flatpak-avoidable
    - slack
