---
- name: DNF | Upgrade the system
  become: true
  dnf:
    name: "*"
    state: latest
  tags:
    - package
    - update
    - dnf

- name: DNF | Install base packages
  become: yes
  package:
    name: [dialog, vrms-rpm, compat-ffmpeg28, langpacks-fr, neofetch, android-tools, adobe-source-code-pro-fonts, python3-psutil.x86_64, java-openjdk, nodejs, npm, xclip, zsh]
    state: present
  tags:
    - package
    - install-packages
    - dnf

- name: DNF | Install programs
  become: yes
  package:
    name: [gnome-tweaks, nautilus-dropbox, keepassxc, transmission, seahorse]
    state: present
  tags:
    - package
    - install-packages
    - dnf

- name: DNF | TEX | Install latex packages
  become: yes
  package:
    name: [texlive-scheme-basic, texlive-babel-french, texlive-hyphen-french, latexmk, texlive-collection-fontsrecommended, texlive-tablefootnote, texlive-wrapfig]
    state: present
  tags:
    - package
    - install-packages
    - dnf
    - latex

- name: DNF | NVIDIA | Instal workstation proprietary driver
  become: yes
  package:
    name: [kernel-devel, kernel-headers, gcc, make, dkms, acpid, libglvnd-glx, libglvnd-opengl, libglvnd-devel, pkgconfig, broadcom-wl, kmod-wl]
    state: present
  tags:
    - packages
    - install-packages
    - desktop
    - dnf
    - nonfree