---
- name: SYSTEM | Change the hostname of the laptop
  become: true
  hostname:
    name: "{{ laptop_hostname }}"
  tags:
    - system
    - hostname

- name: SYSTEM | Change the hostname of the desktop workstation
  become: true
  hostname:
    name: "{{ workstation_hostname }}"
  tags:
    - system
    - hostname
    - desktop

- name: SYSTEM | Create working folder structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/Documents/work"
    - "{{ ansible_env.HOME }}/Documents/work/dev"
    - "{{ ansible_env.HOME }}/Documents/work/dev/web"
    - "{{ ansible_env.HOME }}/Documents/work/dev/android"
    - "{{ ansible_env.HOME }}/Documents/work/dev/other"
    - "{{ ansible_env.HOME }}/Documents/git"
    - "{{ ansible_env.HOME }}/Documents/dev"
  tags:
    - system
    - folder-structure
