---
- name: VSCODIUM | Get Information about latests VSCodium release
  uri: 
    url: https://api.github.com/repos/VSCodium/vscodium/releases/latest
    return_content: true
  register: json_reponse
  tags:
    - vscodium

- name: VSCODIUM | Download latest VSCodium release
  get_url:
    url: "{{ json_reponse.json.assets[0].browser_download_url }}"
    dest: "{{ playbook_dir }}/temp/vscodium.rpm"
  tags:
    - vscodium

- name: VSCODIUM | Installing latest VSCodium release
  become: true
  dnf:
    name: ./temp/vscodium.rpm
    state: present
  tags:
    - vscodium